# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Page.create([
  { :title => "register", :content => "Contact Form", :created_at => "2013-01-14 18:33:53", :updated_at => "2013-01-14 19:13:53" },
  { :title => "why", :content => "", :created_at => "2013-01-14 18:41:35", :updated_at => "2013-01-14 18:41:35" },
  { :title => "contact-us", :content => "<br/>118 / A - Wing, Shoppers Orbit, <br/> Vishrantwadi, Pune - 411015 <br/><br/> #0982388236", :created_at => "2013-01-14 18:58:54", :updated_at => "2013-01-14 19:10:42" },
  { :title => "about-us", :content => "", :created_at => "2013-01-14 18:59:06", :updated_at => "2013-01-14 18:59:29" }
], :without_protection => true )


